//Nutzen Sie dieses Template als Grundlage für die Spezifikation *einzelner* Use-Cases. Diese lassen sich dann per Include in das Use-Case Model Dokument einbinden (siehe Beispiel dort).
ifndef::main-document[include::../_includes/default-attributes.inc.adoc[]]


== Use-Case: UC05 Projektbezogene Daten ändern

=== Kurzbeschreibung

Dieser Use-Case beschreibt die Verwaltung bereits bestehender Projekte durch den Projektleiter oder Manager.

=== Kurzbeschreibung der Akteure

* Projektleiter
* Manager

Möchte Änderungen in einem bestehendem Projekt vornehmen.

=== Vorbedingungen
//Vorbedingungen müssen erfüllt, damit der Use Case beginnen kann, z.B. Benutzer ist angemeldet, Warenkorb ist nicht leer...

Der Projektleiter/Manager besitzt die entsprechenden Zugriffsrechte bzw. die erforderliche Rolle, um Änderungen oder das Hizufügen an/von Projekten vornehmen zu können.


=== Standardablauf (Basic Flow)
//Der Standardablauf definiert die Schritte für den Erfolgsfall ("Happy Path")

. Der Use Case beginnt, wenn der Projektleiter/Manager die Software zur Mitarbeitereinsatzplanung gestartet hat.
. Die Projektleitung meldet sich mit den benutzerbezogenen Anmeldetedaten an.
. Übersicht mit verschiedenen Funktionalitäten wird automatisch geöffnet.
. Auswahl der Funktion: Kalender und der Benutzer wird zur nächsten Seite weitergeleitet.
. Es kann die Auswahl des jeweiligen Projektes vorgenommen werden in dem dieses in der Kalender-Übersicht angeklickt wird.
. Der Benutzer wird zur neuen Seite witergeleitet mit den Stammdaten des Projektes.
. Nun können die jeweiligen Änderungen der Daten vorgenommen werden.
. Abschließend werden alle hinzugefügten Daten über den Button Änderungen Speichern in das System übernommen.
. Der Use Case ist abgeschlossen.


=== Alternative Abläufe
//Nutzen Sie alternative Abläufe für Fehlerfälle, Ausnahmen und Erweiterungen zum Standardablauf

==== <Alternativer Ablauf 1>
Wenn der Benutzer die Bearbeitung des Formulars unter dem Schritt 7. abbricht, ohne dass der Schritt 8. durchgeführt wurde, werden keine Änderungen vorgenommen und das Formular erscheint im Ursprungszustand.


//==== <Alternativer Ablauf 1>
//Wenn <Akteur> im Schritt <x> des Standardablauf <etwas macht>, dann
//. <Ablauf beschreiben>
//. Der Use Case wird im Schritt <y> fortgesetzt.

=== Unterabläufe (subflows)
//Nutzen Sie Unterabläufe, um wiederkehrende Schritte auszulagern
---keine Unterabläufe vorhanden---

//==== <Unterablauf 1>
//. <Unterablauf 1, Schritt 1>
//. …
//. <Unterablauf 1, Schritt n>

=== Wesentliche Szenarios
//Szenarios sind konkrete Instanzen eines Use Case, d.h. mit einem konkreten Akteur und einem konkreten Durchlauf der o.g. Flows. Szenarios können als Vorstufe für die Entwicklung von Flows und/oder zu deren Validierung verwendet werden.
--- keine abweichenden Szenarios vom Standardablauf ---

==== <Szenario 1>
//. <Szenario 1, Schritt 1>
//. …
//. <Szenario 1, Schritt n>

=== Nachbedingungen
//Nachbedingungen beschreiben das Ergebnis des Use Case, z.B. einen bestimmten Systemzustand.
* Das System hat die vollständigen Änderungen des Projektes das bearbeitet wurde gespeichert.
* Falls konkrete Mitarbeiter einem Projekt zugeordnet wurden, so ist diese Zuordnung in der individuellen Einsatzplanung des jeweiligen Mitarbeiters verzeichnet.
//==== <Nachbedingung 1>

=== Besondere Anforderungen
//Besondere Anforderungen können sich auf nicht-funktionale Anforderungen wie z.B. einzuhaltende Standards, Qualitätsanforderungen oder Anforderungen an die Benutzeroberfläche beziehen.
Usability

• Der Use Case gehört zu der grundlegenden Funktionalität des Systems und muss daher eine einfache Bedienbarkeit ermöglichen.

//==== <Besondere Anforderung 1>
