//Nutzen Sie dieses Template als Grundlage für die Spezifikation *einzelner* Use-Cases. Diese lassen sich dann per Include in das Use-Case Model Dokument einbinden (siehe Beispiel dort).
ifndef::main-document[include::../_includes/default-attributes.inc.adoc[]]


== Use-Case: UC03 Hinzufügen von Aufgaben in Projekten

=== Kurzbeschreibung

Dieser Use-Case beschreibt das Einpflegen von speziellen Aufgaben, die in dem jeweiligen Projekt realisiert werden sollen.

=== Kurzbeschreibung der Akteure

Projektleitung

Möchte zur besseren Strukturierung und Aufgabenwahrnehmung in einem Projekt, ausgewählte Aufgaben an Mitarbeiter zuweisen.


=== Vorbedingungen
//Vorbedingungen müssen erfüllt, damit der Use Case beginnen

Die Projektleitung besitzt die entsprechenden Zugriffsrechte bzw. die erforderliche Rolle, um Änderungen an Projekten vornehmen zu können.

=== Standardablauf (Basic Flow)
//Der Standardablauf definiert die Schritte für den Erfolgsfall ("Happy Path")

. Der Use Case beginnt, wenn die Projektleitung die Software zur Mitarbeitereinsatzplanung gestartet hat.
. Die Projektleitung meldet sich mit den benutzerbezogenen Anmeldetedaten an.
. Übersicht mit verschiedenen Funktionalitäten wird automatisch geöffnet.
. Auswahl der Funktion: Projekte verwalten und der Benutzer wird zur nächsten Seite weitergeleitet.
. Ein Umtermenü erscheint, hier kann der Benutzer folgende Funktionen auswählen:
.. neues Projekt hinzufügen
.. Projekt bearbeiten
. Wählt der Benutzer die Funktion ii., öffnet sich ein Filtermenü, mit dessen Hilfe das zu bearbeitende Projekt gesucht werden kann.
. Wurde das entsprechende Projekt ausgewählt, wird der Benutzer zu einem Formular weitergeleitet, welches bereits vorhandene Angaben zu dem Projekt beinhaltet.
. Der Benutzer kann nun Aufgaben im Projekt benennen und diese an die jeweiligen Mitarbeiter vergeben.
. Abschließend werden alle hinzugefügten Daten über den Button Änderungen Speichern in das System übernommen.
. Der Use Case ist abgeschlossen.

=== Alternative Abläufe
//Nutzen Sie alternative Abläufe für Fehlerfälle, Ausnahmen und Erweiterungen zum Standardablauf

Wenn der Benutzer die Bearbeitung des Formulars unter dem Schritt 8. abbricht, ohne dass der Schritt 9. durchgeführt wurde, werden keine Änderungen vorgenommen und das Formular erscheint im Ursprungszustand.

//==== <Alternativer Ablauf 1>
//Wenn <Akteur> im Schritt <x> des Standardablauf <etwas //macht>, dann
//. <Ablauf beschreiben>
//. Der Use Case wird im Schritt <y> fortgesetzt.

=== Unterabläufe (subflows)
//Nutzen Sie Unterabläufe, um wiederkehrende Schritte auszulagern

---keine Unterabläufe vorhanden---

//==== <Unterablauf 1>
//. <Unterablauf 1, Schritt 1>
//. …
//. <Unterablauf 1, Schritt n>

=== Wesentliche Szenarios
//Szenarios sind konkrete Instanzen eines Use Case, d.h. mit einem konkreten Akteur und einem konkreten Durchlauf der o.g. Flows. Szenarios können als Vorstufe für die Entwicklung von Flows und/oder zu deren Validierung verwendet werden.
--- keine abweichenden Szenarios vom Standardablauf ---

//==== <Szenario 1>
//. <Szenario 1, Schritt 1>
//. …
//. <Szenario 1, Schritt n>

=== Nachbedingungen
//Nachbedingungen beschreiben das Ergebnis des Use Case, z.B. einen bestimmten Systemzustand.
* Das System hat die vollständigen Änderungen des Projektes das bearbeitet wurde gespeichert.
* Falls konkrete Mitarbeiter bei der Aufgabenverteilung in einem Projekt benannt wurden, so ist diese Zuordnung in der individuellen Einsatzplanung des jeweiligen Mitarbeiters verzeichnet.

//==== <Nachbedingung 1>

=== Besondere Anforderungen
//Besondere Anforderungen können sich auf nicht-funktionale Anforderungen wie z.B. einzuhaltende Standards, Qualitätsanforderungen oder Anforderungen an die Benutzeroberfläche beziehen.
Usability

• Der Use Case gehört zu der grundlegenden Funktionalität des Systems und muss daher eine einfache Bedienbarkeit ermöglichen.
//==== <Besondere Anforderung 1>
