//Nutzen Sie dieses Template als Grundlage für die Spezifikation *einzelner* Use-Cases. Diese lassen sich dann per Include in das Use-Case Model Dokument einbinden (siehe Beispiel dort).
ifndef::main-document[include::../_includes/default-attributes.inc.adoc[]]


== Use-Case: UC03 Personenbezogene Daten ändern

=== Kurzbeschreibung
Dieser Use-Case beschreibt das Einpflegen neuer Mitarbeiterdaten und die Aktualisierung bestehender Mitarbeiterdaten.

=== Kurzbeschreibung der Akteure

* Manager 
* Administrator 

Möchte Stammdaten eines bestimmten Mitarbeiters der Develappers GmbH ändern und ergänzen.

=== Vorbedingungen
//Vorbedingungen müssen erfüllt, damit der Use Case beginnen kann, z.B. Benutzer ist angemeldet, Warenkorb ist nicht leer...

Benutzer besitzt die entsprechenden Zugriffsrechte bzw. aktuelle Anmeldedaten, um Änderungen an den jeweiligen Stammdaten vornehmen zu können.

=== Standardablauf (Basic Flow)
//Der Standardablauf definiert die Schritte für den Erfolgsfall ("Happy Path")

. Der Use Case beginnt, wenn der Benutzer die Software zur Mitarbeitereinsatzplanung gestartet hat.
. Der Mitarbeiter meldet sich mit den benutzerbezogenen Anmeldetedaten an.
. Übersicht mit verschiedenen Funktionalitäten wird automatisch geöffnet.
. Auswahl der Funktion: Mitarbeiter und der Benutzer wird zur nächsten Seite weitergeleitet.
. Es erscheint eine Übersicht mit allen Mitarbeitern und zusätzlich ein Filtermenü mit dessen Hilfe schneller der Name des entsprechenden Mitarbeiters gefiltert werden kann.
. Es öffnet sich ein Formular, welches bereits gespeicherte Daten des Mitarbeiters beinhaltet:
* Vorname, Name
* Wochenarbeitszeit
* Status (z.Bsp.:Student, Mitarbeiter, Externer)
* Namenskürzel
* Skills
* Abteilung
* geplante/vergangene Auslastungsquote
* Projekt
. Der Benutzer kann die jeweilige Information ändern oder neu erstellen.
. Uber den Button Änderungen Speichern, werden die Aktualisierungen in das System übernommen.
. Der Use Case ist abgeschlossen.

=== Alternative Abläufe
//Nutzen Sie alternative Abläufe für Fehlerfälle, Ausnahmen und Erweiterungen zum Standardablauf

Wenn der Benutzer die Bearbeitung des Formulars unter dem Schritt 7. abbricht, ohne dass der Schritt 8. durchgeführt wurde, werden keine Änderungen vorgenommen und das Formular erscheint im Ursprungszustand.

//==== <Alternativer Ablauf 1>
//Wenn <Akteur> im Schritt <x> des Standardablauf <etwas macht>, dann
//. <Ablauf beschreiben>
//. Der Use Case wird im Schritt <y> fortgesetzt.

=== Unterabläufe (subflows)
//Nutzen Sie Unterabläufe, um wiederkehrende Schritte auszulagern
---keine Unterabläufe vorhanden---

//==== <Unterablauf 1>
//. <Unterablauf 1, Schritt 1>
//. …
//. <Unterablauf 1, Schritt n>

=== Wesentliche Szenarios
//Szenarios sind konkrete Instanzen eines Use Case, d.h. mit einem konkreten Akteur und einem konkreten Durchlauf der o.g. Flows. Szenarios können als Vorstufe für die Entwicklung von Flows und/oder zu deren Validierung verwendet werden.
--- keine abweichenden Szenarios vom Standardablauf ---

//==== <Szenario 1>
//. <Szenario 1, Schritt 1>
//. …
//. <Szenario 1, Schritt n>

=== Nachbedingungen
//Nachbedingungen beschreiben das Ergebnis des Use Case, z.B. einen bestimmten Systemzustand.
* Das System hat die aktualisierten Stammdaten des jeweiligen Mitarbeiters gespeichert.
* Die jeweiligen Stammdaten können nun auch zu Abrechnungszwecken von der Buchhaltung oder anderen verwalterischen Abteilungen der Firma genutzt werden und sind stets aktuell.

//==== <Nachbedingung 1>

=== Besondere Anforderungen
//Besondere Anforderungen können sich auf nicht-funktionale Anforderungen wie z.B. einzuhaltende Standards, Qualitätsanforderungen oder Anforderungen an die Benutzeroberfläche beziehen.
Usability

• Der Use Case gehört zu der grundlegenden Funktionalität des Systems und muss daher eine einfache Bedienbarkeit ermöglichen.


//==== <Besondere Anforderung 1>
