//Nutzen Sie dieses Template als Grundlage für die Spezifikation *einzelner* Use-Cases. Diese lassen sich dann per Include in das Use-Case Model Dokument einbinden (siehe Beispiel dort).
ifndef::main-document[include::../_includes/default-attributes.inc.adoc[]]


== Use-Case: UC03 Zuordnung von Mitarbeitern zu Projekten

=== Kurzbeschreibung

Dieser Use-Case beschreibt die Verteilung von Projekten an bestimmte Projektleiter bzw. Mitarbeiter.

=== Kurzbeschreibung der Akteure

* Manager

Möchte bevorstehende Projekte an Projektleiter zuweisen.

* Projektleiter

Möchte dem ihm zugewiesenen Projekt, Mitarbeiter zuordnen.


=== Vorbedingungen
//Vorbedingungen müssen erfüllt, damit der Use Case beginnen

Der Manager/Projektleiter besitzt die entsprechenden Zugriffsrechte bzw. die erforderliche Rolle, um Änderungen an Projekten vornehmen zu können.

=== Standardablauf (Basic Flow)
//Der Standardablauf definiert die Schritte für den Erfolgsfall ("Happy Path")

. Der Use Case beginnt, wenn der Projektleiter/Manager die Software zur Mitarbeitereinsatzplanung gestartet hat.
. Der Projektleiter/Manager meldet sich mit den benutzerbezogenen Anmeldetedaten an.
. Übersicht mit verschiedenen Funktionalitäten wird automatisch geöffnet.
. Auf dieser Start-Übersicht kann ein Icon mit einem Kalender angeklickt werden.
. Nun wird der Benutzer zum Kalender weitergeleitet und kann bestimmte Zeiträume auswählen in denen Projekte geplant sind.
. Der Benutzer wird nun zur nächsten Seite weitergeleitet.
. Über ein Drop-Down Menü können nun Mitarbeiter ausgewählt werden, die an diesem Projekt, in einem bestimmten Zeitraum arbeiten sollen.
. Abschließend werden alle Änderungen über den Button Änderungen Speichern in das System übernommen.
. Der Use Case ist abgeschlossen.

=== Alternative Abläufe
//Nutzen Sie alternative Abläufe für Fehlerfälle, Ausnahmen und Erweiterungen zum Standardablauf

Wenn der Benutzer die Bearbeitung des Formulars unter dem Schritt 7. abbricht, ohne dass der Schritt 8. durchgeführt wurde, werden keine Änderungen vorgenommen und das Formular erscheint im Ursprungszustand.

//==== <Alternativer Ablauf 1>
//Wenn <Akteur> im Schritt <x> des Standardablauf <etwas //macht>, dann
//. <Ablauf beschreiben>
//. Der Use Case wird im Schritt <y> fortgesetzt.

=== Unterabläufe (subflows)
//Nutzen Sie Unterabläufe, um wiederkehrende Schritte auszulagern

---keine Unterabläufe vorhanden---

//==== <Unterablauf 1>
//. <Unterablauf 1, Schritt 1>
//. …
//. <Unterablauf 1, Schritt n>

=== Wesentliche Szenarios
//Szenarios sind konkrete Instanzen eines Use Case, d.h. mit einem konkreten Akteur und einem konkreten Durchlauf der o.g. Flows. Szenarios können als Vorstufe für die Entwicklung von Flows und/oder zu deren Validierung verwendet werden.
--- keine abweichenden Szenarios vom Standardablauf ---

//==== <Szenario 1>
//. <Szenario 1, Schritt 1>
//. …
//. <Szenario 1, Schritt n>

=== Nachbedingungen
//Nachbedingungen beschreiben das Ergebnis des Use Case, z.B. einen bestimmten Systemzustand.
* Das System hat die vollständigen Änderungen des Projektes gespeichert.
* Die Zugehörigkeit der Mitarbeiter zu einem Projekt ist der individuellen Einsatzplanung des jeweiligen Mitarbeiters verzeichnet.

//==== <Nachbedingung 1>

=== Besondere Anforderungen
//Besondere Anforderungen können sich auf nicht-funktionale Anforderungen wie z.B. einzuhaltende Standards, Qualitätsanforderungen oder Anforderungen an die Benutzeroberfläche beziehen.
Usability

• Der Use Case gehört zu der grundlegenden Funktionalität des Systems und muss daher eine einfache Bedienbarkeit ermöglichen.
//==== <Besondere Anforderung 1>
