= Projektplan: E03-Mitarbeitereinsatzplanung
Hoang Phuong Linh Nguyen <s83710@htw-dresden.de>;
Nils Weber <s84281@htw-dresden.de>; Anh Thu Hoang <s85622@htw-dresden.de>; Luca Leon Wagner <s85265@htw-dresden.de>; Le Quoc Minh Tran <s87560@htw-dresden.de>; Tom Eckhardt <s00000@htw-dresden.de>; Keyur Hareshbhai Kachhadiya <s85495@htw-dresden.de>; Paulina Kostka <s85455@htw-dresden.de>
{localdatetime}
include::../_includes/default-attributes.inc.adoc[]
// Platzhalter für weitere Dokumenten-Attribute


== Einführung
In dem vorliegenden Projektplan werden die Organisation, Arbeitsweise und Ziele des Teams detailliert aufgeschlüsselt.
Die in diesem Kontext erstellten Dokumente werden im Laufe der Projektarbeit ergänzt und verbessert, nach einem neu gewonnenem Kenntnisstand. Ziel des Projektplans ist es eine Organisationsstruktur zu schaffen, sowohl innerhalb des Teams, als auch gegenüber dem Auftraggeber und anderen Beteiligten.


== Projektorganisation

=== Teammitglieder

|===
| *Name* | *Informationen zur Person* | *Rolle*

| Hoang Phuong Linh Nguyen | Wirtschaftsinformatik Eigenschaften: kommunikativ, neugierig| Architect/Analyst 
| Nils Weber | Wirtschaftsingenieurwesen Eigenschaften: kommunikativ, zielstrebig | Project Manager 
|Anh Thu Hoang  | Wirtschaftsinformatik Eigenschaften: kommunikativ, neugierig | Architect/Analyst 
|Luca Leon Wagner  | Wirtschaftsinformatik Eigenschaften: neugierig, kommunikativ, perfektionistisch | Developer 
|Le Quoc Minh Tran  | Wirtschaftsinformatik Eigenschaften: ausdauernd, geduldig  | Architect/Developer
|Tom Eckhardt   | Wirtschaftsingenieurwesen Eigenschaften: kommunikativ | Testing/Analyst
|Keyur Hareshbhai Kachhadiya    | Informatiker Eigenschaften: neugierig, lernt gerne  | Developer/Architect
|Paulina Kostka   | Verwaltungsinformatik Eigenschaften: analytisch, perfektionistisch, kommunikativ | Project Manager/Analyst
|===





//Introduce the project team, team members, and roles that they play during this project. If applicable, introduce work areas, domains, or technical work packages that are assigned to team members. Introduce neighboring projects, relationships, and communication channels. If the project is introduced somewhere else, reference that location with a link.


== Praktiken und Bewertung
//Describe or reference which management and technical practices will be used in the project, such as iterative development, continuous integration, independent testing and list any changes or particular configuration to the project. Specify how you will track progress in each practice. As an example, for iterative development the team may decide to use iteration assessments and iteration burndown reports and collect metrics such as velocity (completed work item points/ iteration).
Grundlegend wird für die Softwareentwicklung und das gesamte Projektmanagement der *Open Unified Process* genutzt. Durch den agilen Entwicklungsprozess werden Praktiken und Arbeitsweisen mit jedem Iterationsschritt kontinuierlich verbessert und erweitert. Dies führt dazu, dass die einzelnen Iterationsschritte, nach der Bearbeitung, nicht vollständig abgeschlossen sind. Vielmehr werden diese öfter aufgenommen und mit neuen Informationen ergänzt oder nach Bedarf verbessert. Durch die iterative Arbeitsweise kann das Team sehr gut auf Änderungen seitens der Stakeholder reagieren. Außerdem kann vermieden werden, dass zu viel Zeit für falsche Lösungen aufgewendet wird. 
Schlussfolgernd ist zu sagen, dass die Einhaltung des Open Unified Prozesses zu einer erfolgreichen Projektumsetzung führt.

Für die Umsetzung erfolgt für jede Phase ein *Teammeeting* in dem besprochen wird, welche Punkte in dem aktuellen Iterationsschritt bearbeitet werden müssen. Es erfolgt ein gemeinsames Brainstorming aus dem hervorgeht welche Teammitglieder die geforderten Aufgaben übernehmen und wie die Umsetzung dieser erfolgen wird. Außerdem erfolgt ein grundlegender Abgleich des Verständnisses, damit jedes Teammitglied auf dem gleichen Stand ist. Im Falle von Fragen werden diese gemeinschaftlich geklärt oder entsprechend dokumentiert, um dies dem Auftraggeber bei dem nächsten Meeting stellen zu können.
Zum Schluss erfolgt ein Resume des Meetings in Form eines zusammengefassten Meilensteins, der in der Projektplanung notiert wird. Detaillierte Informationen zum aktuellen Iterationsschritt werden in der Iterationsplanung niedergeschrieben.

Um unsere strukturierte Arbeitsweise zu unterstützen nutzen wir *Git Hub*, um mittels Issues Aufgaben zu bearbeiten. So kann jedes Teammitglied einsehen, ob eine Aufgabe bereits abgeschlossen wurde, sich noch in Bearbeitung befindet oder einer Änderung bedarf. Außerdem kann durch dieses Vorgehen nichts vergessen werden und jedes Teammitglied kann sich je nach Rolle in die aktuelle Prozessphase einbringen.

Zusätzlich zu GitHub nutzen wir *Notion*. Dieses Programm ermöglicht uns ebenfalls einen Überblick zu behalten über den aktuellen Stand. Desweiteren wird diese Plattform genutzt, um Fragen zu sammeln für das nächste Meeting mit unserem Auftraggeber. So sind die Fragen immer gebündelt und jedes Teammitglied kann seine Fragen dort formulieren, falls sie in der Bearbeitung des jeweiligen Iterationsschrittes aufkommen.
Die *Meetings mit* unserem *Auftraggeber* werden vorallem genutzt, um Lücken zu füllen die aus Mangel an Informationen entstanden sind. Nach jedem solchen Meeting können wir offene Aspekte ergänzen. Diese Vorgehensweise erfolgt in jedem Iterationsschritt.

== Meilensteine und Ziele
//Define and describe the high-level objectives for the iterations and define milestones. For example, use the following table to lay out the schedule. If needed you may group the iterations into phases and use a separate table for each phase

[%header, cols="1,3a,2,1"]
|===
| Iteration
| Primary objectives +
(risks and use case scenarios)
| Scheduled start or milestone
| Target velocity

| I1
|
* Teammitglieder kontaktieren und kennenlernen
* Schwächen und Stärken identifizieren zur Rollenverteilung
* Projektaufgabe verstehen
* Kontakt mit den Auftraggebern herstellen
* Kontakt zum Coach aufnehmen
| 06.11.2023-19.11.2023
| 14

| I2
|
* Meeting mit dem Coach durchführen
* Meetings mit dem Auftraggeber durchführen
* Rollenverteilung im Team vornehmen
* Entwürfe der Vision, Use-Cases, Use-Case-Model
* detaillierte Anforderungen mit dem Auftraggeber herausarbeiten
| 20.11.2023-03.12.2023
| 14

| I3 
|
* Meeting mit dem Coach durchführen
* Meetings mit dem Auftraggeber durchführen
* Entwürfe der Vision, Use-Cases, Use-Case-Model diskutieren und Änderungen besprechen
* Anforderungen des Auftraggebers verfeinerter in die Use-Cases einbinden
* Risikoliste aufstellen
* Projektplan und Iterationspläne 1 und 2 aufstellen
| 04.12.2023-17.12.2023
| 14

| I4 
|
* Meeting mit dem Coach durchführen
* Meetings mit dem Auftraggeber durchführen
* Entwürfe der Vision, Use-Cases, Use-Case-Model final fertigstellen
* Anforderungen des Auftraggebers verfeinerter in die Use-Cases einbinden
* Risikoliste aufstellen
* Projektplan und Iterationspläne 1 und 2 aufstellen
| 04.12.2023-17.12.2023
|===


== Deployment
//Outline the strategy for deploying the software (and its updates) into the production environment.


== Erkenntnisse (Lessons learned)
//List lessons learned from the retrospective, with special emphasis on actions to be taken to improve, for example: the development environment, the process, or team collaboration.

*Problem 1*: Bei der Bearbeitung des Projektes haben wir Redundanzen festgestellt, sodass mehrere thematisch gleiche Dokumente erstllt wurden.
*Lösung 1*: Bisher erstellte Dokumente (Use-Cases) wurden im Team besprochen und zusammengeführt, sodass Redundazen behoben wurden.

*Problem 2*: Mangelhafte explizite Aufgabenverteilung im Team.
*Lösung2*: Aufgabenverteilung erfolgt im Teammeeting und wird unter Git Hub dokumentiert.

*Problem 3*: Aufkommen von Missverständnissen bezüglich der Umsetzung der Anforderungen des Arbeitgebers
*Lösung 3*: Zusammenführung aller Ideen bezüglich der Use-Cases im Teammeeting und Veranschaulichung mithilfe eines Tafelbildes.