@startuml example-usecase-diagram
left to right direction

' skin parameters for usecase with special stereotype
skinparam usecase<<unspezifiziert>> {
  BackgroundColor #eee
  BorderColor #red
  StereotypeFontColor #gray
  StereotypeFontSize 10
}

actor Manager
actor Mitarbeiter
actor Projektleiter


rectangle "Mitarbeitereinsatzplanung" {
  usecase "UC01: Kalender anzeigen" as uc01
  usecase "UC02: Projekt bearbeiten" as uc02
  usecase "UC03: Mitarbeiter auflisten" as uc03
  usecase "UC04: Neue Projekt hinzufügen" as uc04
  usecase "UC05: Benutzerdatei anmelden/abmelden" as uc05
  usecase "UC06: Mitarbeiter bearbeiter" as uc06
  usecase "UC07: Neue Mitarbeiter hinzugefügen" as uc07
}

Manager -- uc01
uc01 -- Mitarbeiter
Manager -- uc02
uc02 -- Mitarbeiter
Manager -- uc03
uc03 -- Mitarbeiter
Manager -- uc04
Projektleiter -- uc04
Manager -- uc05
uc05 -- Mitarbeiter
Manager -- uc06
uc06 -- Mitarbeiter
Manager -- uc07
@enduml